# netlify.toml
[build]
  command = "mkdocs build && bash netlify-build.sh"
  publish = "site"

# Copier les fichiers .htaccess et .htpasswd dans le dossier de publication
[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

# Configuration d'authentification HTTP Basic pour les sections protégées
[[headers]]
  for = "/private/*"
  [headers.values]
    Basic-Auth = "admin:test123"

[[headers]]
  for = "/technical-spec/*"
  [headers.values]
    Basic-Auth = "admin:test123"

[[headers]]
  for = "/functional-spec/*"
  [headers.values]
    Basic-Auth = "admin:test123"

[[headers]]
  for = "/clients/*"
  [headers.values]
    Basic-Auth = "admin:test123"