# netlify.toml
[build]
  command = "mkdocs build && bash netlify-build.sh"
  publish = "site"

# Configuration pour l'authentification HTTP Basic
[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "admin:test123, guest:guest"